// <auto-generated />
using EmployeeDetails.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDetails.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628072328_editSp")]
    partial class editSp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagement.Server.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("dateHired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dateOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("employeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("fName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("contactNumber")
                        .IsUnique();

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("employeeId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            id = 1,
                            address = "123 Main St",
                            contactNumber = "09121234567",
                            dateHired = "2022-01-01",
                            dateOfBirth = "2000-01-01",
                            email = "t9o1oooooo@example.com",
                            employeeId = "IT-0001",
                            fName = "John",
                            gender = "M",
                            lName = "Doe",
                            mName = "Doe",
                            position = "IT",
                            salary = 50000,
                            status = "Active"
                        },
                        new
                        {
                            id = 2,
                            address = "123 Main St",
                            contactNumber = "09121234562",
                            dateHired = "2022-01-01",
                            dateOfBirth = "2000-01-01",
                            email = "t9o1oooo@example.com",
                            employeeId = "HR-0001",
                            fName = "Jane",
                            gender = "F",
                            lName = "Doe",
                            mName = "Doe",
                            position = "HR",
                            salary = 50000,
                            status = "Active"
                        },
                        new
                        {
                            id = 3,
                            address = "123 Main St",
                            contactNumber = "09121234565",
                            dateHired = "2022-01-01",
                            dateOfBirth = "2000-01-01",
                            email = "t9o1oooexample.com",
                            employeeId = "EE-0001",
                            fName = "John",
                            gender = "M",
                            lName = "Doe",
                            mName = "Doe",
                            position = "EE",
                            salary = 50000,
                            status = "Active"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Server.Models.Positions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("positionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("position")
                        .IsUnique();

                    b.HasIndex("positionId")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            position = "Information Technology",
                            positionId = "IT"
                        },
                        new
                        {
                            id = 2,
                            position = "Human Resource",
                            positionId = "HR"
                        },
                        new
                        {
                            id = 3,
                            position = "Electrical Engineer",
                            positionId = "EE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
